### ISSUE TITLE
Switch the RSA code to https://github.com/RustCrypto/RSA

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1133]
Let's use https://github.com/RustCrypto/RSA instead of `ring`.

The main advantage is that it would smoothly compile into WASM.
The main disadvantage is that some operations are apparently not constant times.

cc @dignifiedquire

**Comment by burdges** [comment]
I'd take care with this one.  RSA has nasty vulnerabilities to side channel attacks because signing CRT-style uses p and q separately.  Could we simply disable RSA in WASM?

**Comment by tomaka** [comment]
> Could we simply disable RSA in WASM?

That's what we do at the moment.

**Comment by burdges** [comment]
I skimmed this code, there is the RSA CRT optimizations, but it prevents the worst attacks by verifying the signature after signing.  It's quite a while since I dug into RSA so I've forgotten anything about performance of different approaches.  I suspect better schemes exist overall.  And browser sound very vulnerable to side channel attacks.

**Comment by DemiMarie-parity** [comment]
@burdges I thought browsers exposed native-code RSA implementations.

**Comment by burdges** [comment]
I've never used the web crypto interfaces myself.  I suspect my friend @FlorianDold never used them in GNU Taler, probably because they expose only RSA-PSS of such, but maybe that's good enough here.  If however they expose only RSA-PSS certificates with the CA already in the browsers CA list, then that's pretty useless.

**Comment by DemiMarie-parity** [comment]
[According to MDN](//developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/generateKey) AES (including AES-GCM), ECDSA, and RSA are all supported.  We should use those implementations in the browser, as they are going to be better than anything that can be implemented in JS and/or WASM.  In particular, we can assume that the AES-GCM implementation is hardware accelerated if the platform supports it.

**Comment by tomaka** [comment]
Two notes:

- Right now there's some browser-specific code within secio, but there's also noise. One could argue that the code that calls browser functions should reside in the cryptographic library.

- One difficulty when it comes to AES is that the WebCrypto API is asynchronous. Whenever libp2p wants to emit data, we need to ask the browser to start encrypting, then later retrieve the result and send it out. This makes the implementation really not trivial.

**Comment by DemiMarie-parity** [comment]
I didn’t realize that AES in WebCrypto is asynchronous.  Browsers should probably offer a synchronous version.  RSA key generation is blocking, but AES should not take too long.  There is a reason that Jason Donenfield ditched asynchronous crypto in WireGuard.

In the case of AES and GCM, I think we should either use the WebCrypto API or not support them at all.  Pure-software implementations are slow, vulnerable to timing attacks, or both.  On the other hand, pure-software ChaCha20-Poly1305 can be done with reasonable speed without being vulnerable to timing attacks.

**Comment by thomaseizinger** [comment]
Not happening any time soon, closing for now. We can revisit once the crate is fully audited. See https://github.com/RustCrypto/RSA/issues/60.

**Comment by thomaseizinger** [comment]
The crate has in fact in been audited if one reads the linked issue closely. There was only one low-risk issue found and that one is been fixed.

Switching might be more interesting again not just for WASM but because `ring` doesn't allow us to _export_ the key, see https://github.com/libp2p/rust-libp2p/pull/3681#issuecomment-1497057269.
