### ISSUE TITLE
`nc -z` effectively kills Swarm

### ISSUE THREAD

**Issue by echupriyanov** [libp2p/rust-libp2p#1182]
Probing running Swarm with `nc -z` breaks it.
It is easily reproducible on v0.9.1 with `chat` example:
Terminal windows #1:
```
eric@copoka ~/C/S/rust-libp2p> cargo run --example chat
    Finished dev [unoptimized + debuginfo] target(s) in 1.05s
     Running `target/debug/examples/chat`
Local peer id: PeerId("Qmbe2cZb6gcQcCiHM7C5ferWK6zDTAXzTeu6JbqQn8ad3r")
Listening on "/ip4/127.0.0.1/tcp/63303"
[2019-06-24T08:31:36Z ERROR libp2p_tcp] Failed to get peer address: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }
```
Terminal #2:
```
eric@copoka ~/C/S/rust-libp2p> nc -z localhost 63303
eric@copoka ~/C/S/rust-libp2p> telnet localhost 63303
Trying ::1...
telnet: connect to address ::1: Connection refused
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
eric@copoka ~/C/S/rust-libp2p> 
```

After the first netcat connect, Swarm stops accepting any more connections.

**Comment by twittner** [comment]
Thank you for reporting this bug! I managed to reproduce it with GNU's netcat but not OpenBSD's netcat. The error I got was similar to yours:

> [2019-06-24T09:03:34Z ERROR libp2p_tcp] Failed to get peer address: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }

Looking that the packages it seems that GNU netcat immediately resets the connection so by the time libp2p_tcp attempts to get the peer address from the socket it is no longer in a connected state. I suppose the error you got (code 22) is ultimately for the same reason, most likely the socket has already been disposed by the kernel.

To fix this, libp2p_tcp should ignore sockets for which it can not get the remote address, but should otherwise continue to accept new connections.
