### ISSUE TITLE
Compile errors on parity multihash versions higer than 0.1.1

### ISSUE THREAD

**Issue by pvienhage** [libp2p/rust-libp2p#1303]
Libp2p doesn't build if parity multi-address's version is higher than 0.1.1 because the error enum isn't fully specified on line 134 of the peer_id file.

On this line the enum is under specified:  
https://github.com/libp2p/rust-libp2p/blob/v0.12.0/core/src/peer_id.rs#L134
Because the error defined here has two enum types:
https://github.com/libp2p/rust-libp2p/blob/master/misc/multihash/src/errors.rs#L5

Which creates the error:
error[E0004]: non-exhaustive patterns: `Err(UnsupportedInputLength)` not covered
   --> /Users/pvienhage/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.12.0/src/peer_id.rs:132:15
    |
132 |         match multihash::encode(alg, &enc) {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ pattern `Err(UnsupportedInputLength)` not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms

When the build has fully updated versions of each sub package.

**Comment by tomaka** [comment]
The situation is a bit annoying, because this concerns libp2p 0.12 only. 0.13 does compile.
The proper solution would be to publish multihash 0.2.0 and yank multihash 0.1.1, but then we'd need to release libp2p 0.12.1.

**Comment by thomaseizinger** [comment]
Some of our developers faced this issue as-well but we never had the time to actually dig into _what_ the problem was.

It is understandable that, as the maintainer of a library, supporting older versions is annoying, especially in a phase where you are still iterating on APIs. However, as a user of a library, it is annoying to have your builds break without an explicit version upgrade :(

It would be nice to have that fixed again without having to do the upgrade from 0.12 to 0.13 _now_.

Thank you :)

**Comment by tomaka** [comment]
Nevermind, if we yank multihash 0.1.1, we need to publish 0.13.1, and 0.12.1 isn't needed.

**Comment by tomaka** [comment]
Yanked multihash 0.1.4!
