### ISSUE TITLE
Add a buffering layer in transport::upgrade::Builder

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#1394]
It seems that polling from TCP sockets too often might cause issues.
We could tweak `transport::upgrade::Builder` to optionally do some intermediary buffering.

**Comment by whereistejas** [comment]
Hi, @tomaka ! I would like to work on this issue. I'm still a newbie at Rust. Could you give me a few pointers to get started with this issue?

**Comment by mxinden** [comment]
Hi @whereistejas,

is it that you are generally interested in contributing to rust-libp2p or that you are facing the issue of a large performance impact due to repeated polls of a TCP socket. In case it is the former, I would recommend getting started with one of the issues labeled with [getting-started](https://github.com/libp2p/rust-libp2p/issues?q=is%3Aopen+is%3Aissue+label%3Agetting-started). Just as a note, before you put a lot of work into an issue, please lay out your design in a comment.

**Comment by whereistejas** [comment]
Hi @mxinden I'm generally interested in contributing to rust-libp2p

**Comment by mxinden** [comment]
Great to hear @whereistejas.

I think the easiest one to get started would be https://github.com/libp2p/rust-libp2p/issues/1888. `clippy` would  likely be of some help here. I haven't felt the need for https://github.com/libp2p/rust-libp2p/issues/940 thus far, but maybe others think differently. Next to https://github.com/libp2p/rust-libp2p/issues/1888 I can also recommend tackling https://github.com/libp2p/rust-libp2p/issues/1885.

**Comment by mxinden** [comment]
We would need more data in order to reason about this. In case anyone wants to investigate further, feel free to comment.
