### ISSUE TITLE
Implement floodsub messages authentication and encryption

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#147]

**Comment by romanb** [comment]
As mentioned in https://github.com/libp2p/rust-libp2p/pull/1720#issuecomment-720966812 this effort will probably be subsumed by newer versions of `libp2p-gossipsub` (aka the future `libp2p-pubsub`) which already implements these features since they are part of the pubsub base specification underlying both floodsub and gossipsub.

**Comment by mxinden** [comment]
I am closing here, since I currently see no reason why someone would use floodsub over gossipsub. Please comment in case I am missing something.
