### ISSUE TITLE
Consistency of mplex and yamux settings

### ISSUE THREAD

**Issue by michaelvoronov** [libp2p/rust-libp2p#1531]
At now, mplex and yamux have different naming in setting builder like
`MplexConfig` vs `Config`
`max_num_subtreams` vs `set_max_num_substreams`
`max_buffer_size` vs `set_max_num_substreams`

I think it would be convenient to have the same naming scheme for both mplex and yamux. And for me, yamux scheme looks more impressively.

**Comment by ericjmiller** [comment]
New to Rust, looking to contribute to libp2p.

It seems `mplex` is contained within `rust-libp2p`, while `yamux` is an external module whose API we don't control.  Are you suggesting a change to yamux ([here](https://github.com/paritytech/yamux/blob/develop/src/lib.rs))?

**Comment by mxinden** [comment]
> New to Rust, looking to contribute to libp2p.

@ericjmiller cool.

> while yamux is an external module whose API we don't control.

Not quite. Yamux is an open source project in the sense that it welcomes comments and contributions, but as usual there is no guarantee for those suggestions to be included.

> Are you suggesting a change to yamux (here)?

I would suggest changing the [mplex implementation](https://github.com/libp2p/rust-libp2p/tree/master/muxers/mplex) so that it matches the yamux naming scheme.
