### ISSUE TITLE
Provide a poll method for `StreamMuxer` instances

### ISSUE THREAD

**Issue by Demi-Marie** [libp2p/rust-libp2p#1557]
This would be used to do work, such as sending keep-alive packets, that must happen even if no data is being transmitted.

**Comment by tomaka** [comment]
`poll_inbound` should be able to take that role, no?

**Comment by twittner** [comment]
It  can fulfil that role only until the connection is closing. At that point [we cease calling](https://github.com/libp2p/rust-libp2p/blob/bdbab3239224e47500dbd4ed9ef25cce71e211ad/core/src/connection/manager/task.rs#L319) `StreamMuxer::poll_inbound` and only call [`StreamMuxer::close`](https://github.com/libp2p/rust-libp2p/blob/bdbab3239224e47500dbd4ed9ef25cce71e211ad/core/src/connection/substream.rs#L226). This behaviour triggered #1474.

**Comment by DemiMarie-parity** [comment]
@tomaka @twittner Neither `StreamMuxer::poll_inbound` nor `StreamMuxer::close` can fulfill that role, as neither is guaranteed to be called if we are not able to accept new streams but need to keep the existing streams open.  The contract of `quinn-proto` is that it must be polled regularly no matter what ― otherwise, the connection will time out.  It currently needs to use background tasks for that purpose, which is ugly.  This issue covers adding a `StreamMuxer::poll` method that is guaranteed to be polled if at all possible, even if we can’t actually handle traffic on this `StreamMuxer`.  The easiest way to implement this is to make `StreamMuxer` a subtrait of `Future`.

**Comment by twittner** [comment]
The combination of `StreamMuxer::poll_inbound` and `StreamMuxer::close` does in fact fulfil that role currently. Inbound substreams are always accepted AFAIK.

> The contract of `quinn-proto` is that it must be polled regularly no matter what [...]

This is not a new requirement. Yamux is the same in that regard.

**Comment by DemiMarie-parity** [comment]
> The combination of `StreamMuxer::poll_inbound` and `StreamMuxer::close` does in fact fulfil that role currently. Inbound substreams are always accepted AFAIK.
In that case, this is an issue with the documentation.

**Comment by twittner** [comment]
I do think that the `StreamMuxer` API would benefit from a generic `poll` method which is guaranteed to always be called instead of having two methods.

**Comment by tomaka** [comment]
Feel free to try re-design the `StreamMuxer`.

It has some deficiencies. The ones I can think of are:

- In which state is the muxer left after it returns an error? Can it be polled again/used again? When polling a substream returns an error, is it just about this substream, or the entire connection?

- Would it be possible to make errors more strongly-typed than `io::Error`? Maybe for substreams because they are used as the underlying implementations of the `AsyncRead`/`AsyncWrite` traits whose error type is hardcoded to `io::Error`.

**Comment by DemiMarie-parity** [comment]
@tomaka The policy I used in `libp2p-quic` is:

* If a substream operation fails, the substream should not be used again, but the muxer is unaffected.
* If the muxer itself fails, something has gone very wrong, and other operations will likely fail too.

**Comment by tomaka** [comment]
I've added a `multiplexing` label, for all the issues that should be tackled, possibly at once: https://github.com/libp2p/rust-libp2p/issues?q=is%3Aissue+is%3Aopen+label%3Acategory%3Amultiplexing

> The policy I used in libp2p-quic is:

And we need to compare this against what mplex and yamux do.

**Comment by romanb** [comment]
https://github.com/libp2p/rust-libp2p/pull/1621 introduced `StreamMuxer::poll_event`. Apart from a general redesign or larger refactoring of the `StreamMuxer` API, can this particular issue be considered closed with the introduction of `StreamMuxer::poll_event`?

**Comment by tomaka** [comment]
I do think that `poll_event` would cover that role.
