### ISSUE TITLE
Q: Kademlia closest node algorithm

### ISSUE THREAD

**Issue by michaelvoronov** [libp2p/rust-libp2p#1591]
I am interested in kademlia algorithm of peeking closest nodes. It works now by [zooming in](https://github.com/libp2p/rust-libp2p/blob/fc4dec581e94e6416cb8f325038055235c12009d/protocols/kad/src/kbucket.rs#L323) by distance to the end and then zooming out. So it iterates from found bucket index by `1` in bit representation and then by all `0` ([example](https://gist.github.com/michaelvoronov/cf0c124892a6fa4f191b43c52ac1f03d) for some distance). Zooming in makes it closer to the local node but further from the target node. And what is the intuition behind this process, why are. we iterating by `1`? Why can't we just peek nearest from left and right buckets to the found? Are there any papers describe this process?

Thanks in advance.

**Comment by romanb** [comment]
First note that this is implementation-specific. This algorithm only applies if the routing table is implemented as a "flat array" and not as a dynamically-growing tree, as is actually suggested in the Kademlia paper.

We want to find the `k` closest nodes to some target key `t` from the local routing table (k-buckets). The closest to `t` that we know are obviously in the bucket in which `t` falls, so we start with that. To find the next bucket, however, it is important to remember that we're not interested in the closest  to the local key but to the target key `t`.  Consider the following:

```
3210 (bit positions = buckets)
------------------------------
0000 (local)
0101 (target)
```
Then the buckets cover the following distances (=keys) to the local key:

  * Bucket 3: [2^3, 2^4) => 1000 - 1111
  * Bucket 2: [2^2, 2^3) => 0100 - 0111
  * Bucket 1: [2^1, 2^2) => 0010 - 0011
  * Bucket 0: [2^0, 2^1) => 0001

So if we want to find the closest keys to the target from the buckets, we start with bucket 2, these have distances 0000 - 0011, i.e. 0-3 to the target. If we would next take bucket 1, we would get keys 0010 and 0011 which have distances 7 and 6 from the target, respectively, _because the keys in this bucket differ from the target in bit position 1_. Similarly with bucket 3, because these keys differ from the target in position 3, so have distances >= 8. The keys in bucket 0, however, which is just 0001, agrees with the target in bit position 1 and its distance to the target is 4. So after bucket 2, we need to go to bucket 0. Then we start "zooming out" by going to bucket 1 and then 3, which are bit positions where the local key and target agree, so this is straightforward as we now "move away" from both the local key and the target in terms of xor distance. The first part ("zooming in" if you will) is the one that can be a bit tricky to understand. There is an elaborated example in section 3.3.1, page 23, "Locating the closest nodes to a given ID" of [1].

[1] https://pub.tik.ee.ethz.ch/students/2006-So/SA-2006-19.pdf

**Comment by michaelvoronov** [comment]
Thank you for the answer, will take a look 👍

**Comment by mxinden** [comment]
I am closing this issue for now. @michaelvoronov feel free to (re-) open (another) issue in case you have further questions.
