### ISSUE TITLE
Should `ProtocolsHandler` get a `InboundOpenInfo` type?

### ISSUE THREAD

**Issue by twittner** [libp2p/rust-libp2p#1709]
When `libp2p-request-response` was introduced, it used a combination of upgrades and channels which was seen as a ["natural continuation"](https://github.com/libp2p/rust-libp2p/pull/1596#discussion_r446000828) of the original approach to negotiate protocols. Timeout handling in the context of this approach proved to be difficult (see #1706) because identifying upgrades and upgrade errors is not always possible for inbound upgrades. It seems that the `ProtocolsHandler` trait is missing a type `InboundOpenInfo` which would be available in upgrade callbacks, mirroring the already existing `OutboundOpenInfo` type. This ticket is about the question if others see the need for such a type or not?

**Comment by tomaka** [comment]
I know this isn't really documented, but in my mind it would be the other way around: the `OutboundOpenInfo` would be deprecated.

The user is free to pass any "meta-data" inside of the `OutboundProtocol` (and `InboundProtocol`) itself, and the `OutboundOpenInfo` is a redundant mechanism.

**Comment by twittner** [comment]
This only applies to successful upgrades and does not help with upgrade errors, no?

**Comment by romanb** [comment]
I don't see another or better approach to attach context information to inbound upgrades that is also available in the error case. Adding to that the fact that the `multi` handler cannot even be implemented correctly without such context (as seen in https://github.com/libp2p/rust-libp2p/pull/1710) it seems rather important. `libp2p-request-response` is relying on `inject_listen_upgrade_error` to be called properly, otherwise all inbound request failures are silent. While this doesn't have immediate fatal consequences (i.e. memory leaks or anything like it), it is still very undesirable, not just for `Throttled`, since, if I remember correctly, https://github.com/paritytech/substrate/pull/6634 even uses the `multi` handler at the moment. So I'm :+1: for `InboundOpenInfo`.

**Comment by twittner** [comment]
Another implication of `{In,Out}boundUpgradeExt::map_{in, out}bound` and `{In, Out}boundUpgradeExt::map_{in, out}bound_err` is that they usually create closure types which in turn require boxing in order be named as associated `ProtocolsHandler::{In, Out}boundProtocol`s.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/1714.
