### ISSUE TITLE
Publish latest parity-multiaddr

### ISSUE THREAD

**Issue by rklaehn** [libp2p/rust-libp2p#1723]
`parity-multiaddr` contains a few tiny changes since 0.9.1 that have not yet been published.

I had expected libp2p 0.24.0 to include these changes, but this is not the case. Could you please publish the latest `parity-multiaddr` and make a libp2p 0.24.1 or whatever that depends on the new parity-multiaddr version so everything is up to date again?

**Comment by romanb** [comment]
`parity-multiaddr-0.9.2` [is published](https://crates.io/crates/parity-multiaddr/0.9.2). There doesn't seem to be a need for `libp2p-0.24.1`. The reason these changes were not released yet is because it was forgotten to add a changelog entry for https://github.com/libp2p/rust-libp2p/pull/1653. Whether a crate is a candidate for a release is primarily determined based on the continuously updated changelogs.

**Comment by rklaehn** [comment]
Thanks. Will make sure to include a changelog entry in the future.
