### ISSUE TITLE
`pnet` crate is not included in workspace but present in dependencies

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#1817]
The code in this crate is - I think - never built because it is not included in the workspace members: https://github.com/libp2p/rust-libp2p/blob/421ae9d9c9cfe1398f8bf6e2dd7d90c8e8f36018/Cargo.toml#L100-L125

It looks this is dead and outdated code? It doesn't even depend on `libp2p-core`?

**Comment by romanb** [comment]
Since it is a dependency of `libp2p` with a `path`, the local code does get built. The `libp2p` crate further exposes `pub fn build_tcp_ws_pnet_noise_mplex_yamux()` for development purposes. I think its neither outdated nor dead. It was probably just an oversight that it was not added to the workspace in https://github.com/libp2p/rust-libp2p/pull/1385. `libp2p-core` was simply an unused dependency (see https://github.com/libp2p/rust-libp2p/pull/1429) as the current integration of `libp2p-pnet` is based on `AsyncRead` / `AsyncWrite` only, as far as I can tell.

**Comment by thomaseizinger** [comment]
Thanks for the answer @romanb !

I should have looked further into it then! I opened the issue because my IDE flagged this code as not being included anywhere hence the assumption that it is actually not being built.
