### ISSUE TITLE
Gossipsub: Publish error after idle network.

### ISSUE THREAD

**Issue by elenaf9** [libp2p/rust-libp2p#2034]
I am not sure if this behavior is deliberate, but there are problems when trying to publish a message to a topic after no message has been send for the last ~30 seconds.

If no messages are send in a gossip-sub network for some time, the peers disconnect from each other. 
If then a peer tries to publish a message to a topic it causes an Publish Error: Insufficient Peers, even though it was initially successful directly after the peers connected.
From what I tested, this also happens when the other peer has been added to the explicit peers.
This issue can be reconstructed with the gossipsub-chat example:

1.  start both peers (with the second peer adding the first peer's information as arguments, like instructed in the gossipsub-chat  example file)
2. send messages -> will be successful
3. don't send a message for ~30 seconds
4. try to send a message -> `Publish error: InsufficientPeers`

I guess the reason for this behavior is that a message is only published if there are any peers in the `topic_peers` map for that topic, but on `inject_disconnected` a peer is removed from all topics.

If this is behavior was implemented on purpose, could you please point out to me how an idle connection can be solved / handled in gossipsub?

**Comment by mxinden** [comment]
Thanks for the detailed description @elenaf9.

@AgeManning can you help here?

**Comment by AgeManning** [comment]
Hi @elenaf9 

Thanks for raising this. This is in fact a bug. I've submitted a PR which should fix this: https://github.com/libp2p/rust-libp2p/pull/2043

I think this issue is actually worse than you report. 

Even if messages are sent between peers, the peers will disconnect at exactly 30 seconds. I'm personally using a custom implementation of the libp2p NetworkBehaviour, which is why I hadn't noticed this earlier. 

Thanks again for raising this!

**Comment by elenaf9** [comment]
Fixed with #2043.
