### ISSUE TITLE
protocols/kad: debug_assert panic - expecting disconnected peer not to be connected

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2092]
I triggered the panic below with https://github.com/mxinden/rust-libp2p-server/. Unable to reproduce thus far.

```
thread 'main' panicked at 'assertion failed: !self.connected_peers.contains(disconnected.preimage())', /home/mxinden/.cargo/git/checkouts/rust-libp2p-800b9a7842b0accc/6b2873b/protocols/kad/src/behaviour.rs:1033:33
```

https://github.com/libp2p/rust-libp2p/blob/3b0f5a4f9630a6f51c277843bf669c1b30e2f74b/protocols/kad/src/behaviour.rs#L1024-L1025

Is the `debug_assert` to strict?

**Comment by FelipeRosa** [comment]
I'm currently working on a personal project and this one pops quit often for me. I'm a bit new to libp2p in general, why is that `debug_assert` needed?

**Comment by mxinden** [comment]
> I'm currently working on a personal project

:tada: 

Thanks for following up here @FelipeRosa.

> why is that debug_assert needed?

It is supposed to uphold that there is no state mismatch between routing table and connected peers tracked in the Kademlia `NetworkBehaviour`.

I haven't gotten around to further debugging this. In case you are able to reproduce this reliably, could you share a minimal reproducible example here @FelipeRosa?

**Comment by FelipeRosa** [comment]
Hey @mxinden,

Thanks for the quick reply.

> I haven't gotten around to further debugging this. In case you are able to reproduce this reliably, could you share a minimal reproducible example here @FelipeRosa?

I'm not able to reproduce this issue consistently. I read a bit of the libp2p_kad code to try to understand where this might be coming from but I didn't quite wrap my head around it yet.

What I did try to do is create a little program to keep generating hashes that would fall into buckets with available space in them and then making `get_closest_peers` calls sequentially. 

Something like this but with some code to wait for queries to finish:
```rust
let rand_bytes: [u8; 32] = rng.gen();
let ma = libp2p::multihash::Sha2_256::digest(&rand_bytes).as_ref().to_vec();

if let Some(bucket) = swarm.behaviour_mut().kbucket(ma.clone()) {
    if !bucket.has_pending() {
        swarm.behaviour_mut().get_closest_peers(ma);
    }
}
```

My guess is that by doing this I would keep having peers connecting and disconnecting to generate as many routing table states as possible in order to reach the one which causes this bug.

Do you have any suggestions for things I could try?

**Comment by izolyomi** [comment]
I also experienced this bug during my recent experiments with libp2p, but could not reliably reproduce it.
