### ISSUE TITLE
Inconsequent Kademlia bootstrapping events

### ISSUE THREAD

**Issue by izolyomi** [libp2p/rust-libp2p#2121]
Following events coming from the Kademlia protocol, I always receive bootstrapping events in the following pattern:

```
BootstrapOk { peer: PeerId("12D3KooWAYFzVvNfpu8j6HZ8cS6tXngRe8kLXCrwEeXBw86JG9h6"), num_remaining: 11 }
...
BootstrapOk { peer: PeerId("1AkytfpPb2r6xtH8UtKE3EADBUbGjRuKWRjE5EgbtBTJpd"), num_remaining: 0 }
BootstrapOk { peer: PeerId("1AauQwngUA6DWkBHWwfqHMDQB4eum5GViciWvPsnCtM6ke"), num_remaining: 0 }
```

I.e. there are always two different events with `num_remaining: 0` at the end. I think there must be a bug in either the discovery algorithm or the counter (for remaining peerids to be discovered) has an off by one error.

I've also seen that the initial value of the counter varies from 11 to 13. This might be normal to be undeterministic though, I'm not completely familiar with all internal details of this DHT implementation.

**Comment by mxinden** [comment]
> I.e. there are always two different events with num_remaining: 0 at the end. I think there must be a bug in either the discovery algorithm or the counter (for remaining peerids to be discovered) has an off by one error.

Great catch @izolyomi! From taking a quick look, the issue seems to be here:

https://github.com/libp2p/rust-libp2p/blob/c1ef4bffd225a78cefe8fa43dc8ee18e03ff4f93/protocols/kad/src/behaviour.rs#L1108-L1124

The code does two things:

1. Spawn the next Query via `self.queries.continue_iter_closest`.
2. Report the result of the previous query via `OutboundQueryCompleted`.

`num_remaining` is calculated for the _freshly spawned_ query, instead of for the _just finished_ query. A change along the lines of the below should fix it:

```diff
- let num_remaining = remaining.len().saturating_sub(1) as u32;
+ let num_remaining = remaining.len() as u32;
```

@izolyomi do you want to send in a patch?

---

> I've also seen that the initial value of the counter varies from 11 to 13. This might be normal to be undeterministic though, I'm not completely familiar with all internal details of this DHT implementation.

This is normal. The variation is the result of the code below:

https://github.com/libp2p/rust-libp2p/blob/c1ef4bffd225a78cefe8fa43dc8ee18e03ff4f93/protocols/kad/src/behaviour.rs#L1073-L1106

**Comment by izolyomi** [comment]
Thanks for the quick reply and the confirmation. I've also had a suspicion for the `saturating_sub()` being guilty here, but all the surrounding logic was yet beyond my limited understanding.

As the patch seems to be trivial, I can easily send a one-liner if you prefer the usual Github PR workflow, but feel free to resolve it in any faster way if that's more practical on your side. 🤷
