### ISSUE TITLE
Can we get a new version pushed to crates.io please?

### ISSUE THREAD

**Issue by gilescope** [libp2p/rust-libp2p#2273]
The latest code doesn't depend on the deprecated https://crates.io/crates/cpuid-bool/0.1.2 crate any more (thanks to soketto 0.7 upgrading their sha-1 crate).

**Comment by mxinden** [comment]
Happy to cut a new release, though `master` branch is currently broken (see https://github.com/libp2p/rust-libp2p/issues/2242). That will be fixed with https://github.com/libp2p/rust-libp2p/pull/2248.

My plan thus far was to wait for https://github.com/libp2p/rust-libp2p/pull/2248 to merge and then cut a release candidate and later on a full release. Why a release candidate first? (1) it is a pretty large release and (2) https://github.com/libp2p/rust-libp2p/pull/2248 is a large change literally at the core (`libp2p-core`) of rust-libp2p.

Would that work for you @gilescope? Does the above issue currently block you in any way?

**Comment by gilescope** [comment]
I'm sure those timescales will be fine. At some point there might need to be another one when I finally get rand upgraded (but that's not likely to be a quick thing).

**Comment by mxinden** [comment]
I just published a release candidate (see https://github.com/libp2p/rust-libp2p/pull/2290#issuecomment-944191711). Giving some time for people to test the release candidate. In case nothing comes up, I will cut a new release.

**Comment by mxinden** [comment]
Closing here since `v0.40.0` and `v0.41.0` have been released.
