### ISSUE TITLE
core/src/connection/listeners: Use FuturesUnordered instead of VecDeque

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2276]
https://github.com/libp2p/rust-libp2p/blob/937b59de8946eb3773e292691dac4e5f3e081706/core/src/connection/listeners.rs#L87-L90

I think we should really use a `FuturesUnordered` here.

> This structure is optimized to manage a large number of futures. Futures managed by FuturesUnordered will only be polled when they generate wake-up notifications. This reduces the required amount of work needed to poll large numbers of futures.

https://docs.rs/futures/0.3.17/futures/stream/struct.FuturesUnordered.html

**Comment by thomaseizinger** [comment]
I've had good experiences with `FuturesUnordered`. The only pitfall to watch out for is that it must never get empty if you want to push to it again.

Hence I like to initialize it with `future::pending()` for cases like this where it is held permanently as a field rather than used as part of `collect`.

**Comment by mexskican** [comment]
@mxinden I think `SelectAll` would be a better fit in this case, the `Listener` struct contains a stream and `listeners` is a set of streams that needs to be polled.
https://docs.rs/futures/0.3.17/futures/stream/select_all/struct.SelectAll.html

**Comment by mooori** [comment]
`SelectAll<BoxStream<'static, TTrans::Listener>>` requires additional trait and lifetime bounds:
```rust
TTrans::Listener: Send + 'static
```

This propagates to other modules, e.g. `Network<TTrans, THandler>` will then require those bounds as well.

Is it ok to add those bounds? Or maybe someone has an idea for a workaround or another approach?

I think `FuturesUnordered<BoxFuture<'static, ListenersEvent<TTrans>>>` requires additional `Send + 'static` bounds as well for `TTrans::Error` and `TTrans::ListenerUpgrade`.

**Comment by mxinden** [comment]
Ah, haven't seen `SelectAll` before. Thanks for bringing it up.

> `SelectAll<BoxStream<'static, TTrans::Listener>>` requires additional trait and lifetime bounds:
> 
> ```rust
> TTrans::Listener: Send + 'static
> ```

I haven't looked deeper into this. @mooori why are those additional bounds needed?

@mexskican @mooori is either one of you interested in proposing a patch?

**Comment by mooori** [comment]
@mxinden `<TTrans as Transport>::Listener` cannot be unpinned, so I'd wrap it in `BoxStream`. I was thinking about adding a field to `ListenersStream`:

```rust
streams: SelectAll<BoxStream<'static, TTrans::Listener>>
```

Then, the additional bounds are needed as `BoxStream` is [defined as](https://docs.rs/futures/0.3.17/futures/stream/type.BoxStream.html):

```rust
pub type BoxStream<'a, T> = Pin<Box<dyn Stream<Item = T> + Send + 'a, Global>>;
```

I couldn't find a way to replace `VecDeque` by `SelectAll` without requiring additional bounds.

That's why I was wondering if it is ok to add them? Or maybe I missed something and there's an approach which doesn't require additional bounds?

If this can be sorted out, I'd like to work up a PR.

**Comment by mxinden** [comment]
Thanks for the comment above @mooori!

Given that the set of listeners is polled on a single futures task, would a [`LocalBoxStream`](https://docs.rs/futures/0.3.18/futures/stream/type.LocalBoxStream.html) suffice?

> If this can be sorted out, I'd like to work up a PR.

:pray:

**Comment by thomaseizinger** [comment]
Listeners are now part of the transport.
