### ISSUE TITLE
gossipsub: publish should take a topic hash and topic hash should be constructible from a [u8; 32]

### ISSUE THREAD

**Issue by dvc94ch** [libp2p/rust-libp2p#2284]

**Comment by AgeManning** [comment]
Not entirely sure what you're chasing here. 

The idea for publishing is that you know the topic and you can send the topic to publish on.  The other public functions, such as `subscribe()` and `unsubscribe()` also take a `Topic` has an input parameter. 

You can define how you want to hash your topic. If you have a set of random bytes and want to publish on a topic that represents those random bytes, you can use the `IdentityHash` type (https://github.com/libp2p/rust-libp2p/blob/master/protocols/gossipsub/src/topic.rs#L35). 

i.e, something like: 
```rust
let topic = Topic<IdentityHash>::new(String::from_utf8_lossy(bytes))
```
When you publish on this, the hash is the same as the input, so effectively you are sending on the raw bytes (provided they can be converted to a string). 

You can't just use an arbitrary 32 byte array, because a topic must be sent as a Protobuf `String`, which doesn't allow arbitrary bytes. This is why `Topic` can only be created from objects that implement `Into<String>`.

**Comment by dvc94ch** [comment]
I'm using a public key as the topic. Base64 encoding it and then taking the hash seems wasteful. Why is something other than the TopicHash sent over the network?

**Comment by AgeManning** [comment]
I guess a Topic could store bytes and then the "hash" which in your case is `base64` converts the bytes to a String. 

The reason a `Topic` currently stores a `String` is to prevent conversions when using the `IdentityHash`. I.e people just doing a 1to1 for `Topic` <> `TopicHash`. 

You could just put your base64 encoding of your public key as a `Topic<IdentityHash>` and send that. The `IdentityHash` means the string you put into the topic will be sent over the network as is. There is no extra hashing involved. 

The point of the `Hasher` trait is to allow users to implement their own hash, which converts a `Topic` to a `TopicHash` which gets sent over the network.

**Comment by AgeManning** [comment]
Just to re-iterate. 

The only thing sent over the network is the `TopicHash`. In the specs it was suggested that all topics (which were originally strings) should be hashed and the hash is what people subscribe to. 

The kind of hash is up to the user. We left the hash type up to the user by introducing the `Hasher` trait which converts a `Topic` to a `TopicHash`. We implemented an `IdentityHash` which bypasses the hashing mechanism altogether allowing you to just use `Topic` which effectively is the same thing as a `TopicHash` if you don't want to do any hashing.

**Comment by dvc94ch** [comment]
So then there is no reason why I can't just use the public key as the topic hash. I don't care about compatibility with go ipfs. Should I open a PR?

**Comment by AgeManning** [comment]
Perhaps you have not understood what I've been saying. 

You can already do what you want. 
If you want to publish a message on a topic that's based on your public key, do the following:
```rust
gossipsub.publish(Topic<IdentityHash>::new(x), data)
```
Where `x` is the base64 encoding of your public key and data is the data you want to send on the topic. 

This will publish a message on topic where you are "just using the public key as the topic hash"

**Comment by dvc94ch** [comment]
I do understand, and that is what I am currently doing. I just don't understand why I need to encode/decode a byte slice to base64 for no good reason. Everytime I get a message I need to decode the topic to figure out the "real" topic.

To elaborate on what I don't understand, why does a networking protocol mandate that the topic be a utf8 string. It seems like an arbitrary restriction.

So what I'm suggesting is removing the hasher and the `Topic` abstraction and let the user use an arbitrary topic hash. If the protocol mandates it you can make it fixed length, if not just take a `Vec<u8>`.

**Comment by AgeManning** [comment]
As I was saying, the specifications require a protobuf `String`. (https://github.com/libp2p/specs/tree/master/pubsub#the-message). 

Your PR would then cause the rust-implementation of gossipsub to be non-spec compliant. If you don't want to base64 encode/decode (or use a topic string) then I think you have two options:
- Create a PR to the libp2p specs to change the protobuf format to use bytes (this is a non-backwards compatible change, which might be difficult for current gossipsub implementations, which is why I suspect it hasn't be done before). 
- Fork this implementation and go off-spec to work within your own network.
