### ISSUE TITLE
core/: Report pending connection being aborted

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2329]
Today when aborting a pending connection, we remove the pending connection from `Pool::pending` directly:

https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L974-L978

Later on, when the task reports that it has been aborted, the `Pool` checks if it has an entry in `Pool::pending`, which it does not, thus dropping the error instead of reporting it.

https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L894-L899

We should instead report the pending connection being aborted by emitting an event.

**Comment by JerryHue** [comment]
@mxinden, hello! Could I try to look into this?

**Comment by mxinden** [comment]
@JerryHue sure thing. Help here is very much appreciated.

Unit test should be fairly simple, checking for a `PendingConnectionError::Aborted` after aborting a pending connection.

**Comment by MarcoPolo** [comment]
@JerryHue have you started working on this? If not, do you mind if I pick this up? Thanks!

**Comment by JerryHue** [comment]
Hello, @MarcoPolo! I will start to work on this today. If by the end of the day I couldn't advance much, I will delegate it to you. Is that alright?

**Comment by MarcoPolo** [comment]
Of course!

**Comment by JerryHue** [comment]
@MarcoPolo, hello! I read through the code, but I feel like this might be a little bit too much for me, especially since I am not familiar with this part of the core (I only worked with `PeerId`s, which arguably, were an easier concept for me).

Sorry for the inconvenience, and thank you for the prompt responses, @mxinden and @MarcoPolo.

**Comment by MarcoPolo** [comment]
@mxinden could you assign this to me please?

**Comment by jmmaloney4** [comment]
@MarcoPolo are you working on this? Do you mind if I take a stab?

**Comment by MarcoPolo** [comment]
yep! please take!

**Comment by jmmaloney4** [comment]
Hi @mxinden, I have a few questions about the code.

Will both of these be needed?

https://github.com/libp2p/rust-libp2p/blob/245b0563ab41a37b52d1d45ddb59f8706e130a53/core/src/connection/pool.rs#L978-L981

https://github.com/libp2p/rust-libp2p/blob/245b0563ab41a37b52d1d45ddb59f8706e130a53/core/src/connection/pool.rs#L902-L904

I'm assuming the ones in `abort` should be removed, and the `PendingConnection` should be removed from the hashmap and have the counter decremented in the `Pool::poll` method instead. Does this sound correct? 

A follow up: If the above is correct and I remove both those actions from the `PendingConnection::abort` method, how does the connection get aborted? Those are the only two things the `abort` method does? I see that here:

https://github.com/libp2p/rust-libp2p/blob/245b0563ab41a37b52d1d45ddb59f8706e130a53/core/src/connection/pool.rs#L717

We pull events from a queue, and I think we want there to be a `PendingConnectionEvent::PendingFailed` event with a `PendingConnectionError::Aborted` in the error field, which we then return from the `Pool::poll` method. I hope I'm putting the pieces together correctly. 

So, where does/should this `PendingConnectionError::Aborted` come from? It seems like the only method that calls the `PendingConnection::abort` method is the `Pool::disconnect` method here

https://github.com/libp2p/rust-libp2p/blob/245b0563ab41a37b52d1d45ddb59f8706e130a53/core/src/connection/pool.rs#L421-L425

And I can't find anything in that method that seems to generate an event. Some guidance would be appreciated. Thanks! -Jack

**Comment by MarcoPolo** [comment]
Thanks for looking into this @jmmaloney4! Some thoughts:

1. When we abort a pending connection we drop the [PendingConnectionInfo](https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L133) object. This drops the notifier which closes the oneshot channel.
2. The task gets notified that the notifier dropped and adds the aborted event [here](https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool/task.rs#L116) (and the equivalent inbound version [here](https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool/task.rs#L155))
3. So the aborted event is already being propagated to the pool, but it isn’t getting returned by the Pool’s Poll method because there’s no else statement in the [if let](https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L894)
4. [PendingOutboundConnectionError](https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L192) needs a handler and Option<peer>. So we’ll need to preserve the handler/peer info to send back a proper error.
6. We should make sure there are no weird race conditions in the Pool’s poll if we remove the entry (I’m thinking about [this](https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L733) case specifically but maybe there are others – but maybe this is a none issue since the task will stop advancing as soon as it gets the cancellation signal.)
7. PendingConnection is a public struct (should it be? that’s a different q)
8. PendingConnection.abort is also public.

As long as we can send back the proper PoolError then we should be set. The current blockers seem to be that we lose the handler/Option<peerid> when we drop the entry.

I’d advise against not changing the public interface to `PendingConnection`.

There’s a couple different solutions so feel free to pick your own, but I personally would probably send a special value to the task itself telling it that we want to abort this pending connection via the field currently called `_drop_notifier` (and rename that field to drop_or_abort_notifier). Not have the abort method remove the entry or decrement the counter. And I think that should just work.

Good luck! let me know if anything above is unclear and I can try to elaborate :)

**Comment by mxinden** [comment]
> There’s a couple different solutions so feel free to pick your own, but I personally would probably send a special value to the task itself telling it that we want to abort this pending connection via the field currently called _drop_notifier (and rename that field to drop_or_abort_notifier). Not have the abort method remove the entry or decrement the counter. And I think that should just work.

Agreed. 

How about something along the lines of the below?

```diff
diff --git a/core/src/connection/pool.rs b/core/src/connection/pool.rs
index 59d41908..2df0770d 100644
--- a/core/src/connection/pool.rs
+++ b/core/src/connection/pool.rs
@@ -136,8 +136,8 @@ struct PendingConnectionInfo<THandler> {
     /// Handler to handle connection once no longer pending but established.
     handler: THandler,
     endpoint: PendingPoint,
-    /// When dropped, notifies the task which then knows to terminate.
-    _drop_notifier: oneshot::Sender<Void>,
+    /// Channel to command the task to abort.
+    abort_notifier: Option<oneshot::Sender<()>>,
 }
 
 impl<THandler: IntoConnectionHandler, TTrans: Transport> fmt::Debug for Pool<THandler, TTrans> {
@@ -955,7 +955,6 @@ pub enum PoolConnection<'a, THandler: IntoConnectionHandler> {
 /// A pending connection in a pool.
 pub struct PendingConnection<'a, THandler: IntoConnectionHandler> {
     entry: hash_map::OccupiedEntry<'a, ConnectionId, PendingConnectionInfo<THandler>>,
-    counters: &'a mut ConnectionCounters,
 }
 
 impl<THandler: IntoConnectionHandler> PendingConnection<'_, THandler> {
@@ -976,8 +975,9 @@ impl<THandler: IntoConnectionHandler> PendingConnection<'_, THandler> {
 
     /// Aborts the connection attempt, closing the connection.
     pub fn abort(self) {
-        self.counters.dec_pending(&self.entry.get().endpoint);
-        self.entry.remove();
+        if let Some(notifier) = self.entry.get_mut().drop_notifier.take() {
+            notifier.send(task::PendingConnectionCommand::Abort)
+        }
     }
 }
 
diff --git a/core/src/connection/pool/task.rs b/core/src/connection/pool/task.rs
index 9062583f..86581166 100644
--- a/core/src/connection/pool/task.rs
+++ b/core/src/connection/pool/task.rs
@@ -41,9 +41,15 @@ use futures::{
 use std::pin::Pin;
 use void::Void;
 
-/// Commands that can be sent to a task.
+/// Commands that can be sent to a task driving a pending connection.
 #[derive(Debug)]
-pub enum Command<T> {
+pub enum PendingConnectionCommand<T> {
+    Abort,
+}
+
+/// Commands that can be sent to a task driving an established connection.
+#[derive(Debug)]
+pub enum EstablishedConnectionCommand<T> {
     /// Notify the connection handler of an event.
     NotifyHandler(T),
     /// Gracefully close the connection (active close) before
@@ -103,13 +109,16 @@ pub enum EstablishedConnectionEvent<THandler: IntoConnectionHandler> {
 pub async fn new_for_pending_outgoing_connection<TTrans>(
     connection_id: ConnectionId,
     dial: ConcurrentDial<TTrans>,
-    drop_receiver: oneshot::Receiver<Void>,
+    abort_receiver: oneshot::Receiver<PendingConnectionCommand>,
     mut events: mpsc::Sender<PendingConnectionEvent<TTrans>>,
 ) where
     TTrans: Transport,
 {
-    match futures::future::select(drop_receiver, Box::pin(dial)).await {
+    match futures::future::select(abort_receiver, Box::pin(dial)).await {
         Either::Left((Err(oneshot::Canceled), _)) => {
+            unreachable!("Pool never drops channel to task.");
+        }
+        Either::Left((Ok(PendingConnectionCommand::Abort), _)) => {
             let _ = events
                 .send(PendingConnectionEvent::PendingFailed {
                     id: connection_id,
@@ -117,7 +126,6 @@ pub async fn new_for_pending_outgoing_connection<TTrans>(
                 })
                 .await;
         }
-        Either::Left((Ok(v), _)) => void::unreachable(v),
         Either::Right((Ok((address, output, errors)), _)) => {
             let _ = events
                 .send(PendingConnectionEvent::ConnectionEstablished {
```

**Comment by jmmaloney4** [comment]
Thanks for the pointers @MarcoPolo  @mxinden. I have run into an issue now where the `PendingConnection::abort` method takes an immutable owned `self`, but calling `self.entry.get_mut()` requires a mutable `self`. I'm a bit of a rust beginner so I'm not sure if there is a good way to handle this without modifying the public interface of `PendingConnection`, but my intuition leads me to believe some kind of cell or smart pointer might do the trick, but I know these usually bring threading issues. What are your thoughts? 

Also, when thinking about the potential race condition here:

https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L725-L733

when the pending connection has already been removed in the abort handler, I believe the proper behavior should just be to continue to abort the connection. I think this can be handled by switching the `.expect()` out for a `if let` style guard as here:

https://github.com/libp2p/rust-libp2p/blob/8b68026bb04a469654020a8dcfe68308404e2510/core/src/connection/pool.rs#L894-L899

I think the other case that could happen is that the abort message beats the successfully connected message. What then? The PendingConnection will have been removed from the list. Is it enough to just not handle the successfully connected message? Or do we need to do some cleanup of the connection and inform the other end that it has been aborted?

**Comment by MarcoPolo** [comment]
I think you can just put `mut` in front of the `self` param like so:

```
diff --git a/core/src/connection/pool.rs b/core/src/connection/pool.rs
index 163da217..a6d49dc4 100644
--- a/core/src/connection/pool.rs
+++ b/core/src/connection/pool.rs
@@ -972,7 +972,7 @@ impl<THandler: IntoConnectionHandler> PendingConnection<'_, THandler> {
     }
 
     /// Aborts the connection attempt, closing the connection.
-    pub fn abort(self) {
+    pub fn abort(mut self) {
         self.counters.dec_pending(&self.entry.get().endpoint);
         self.entry.remove();
     }
```

It doesn't change the signature because it already takes the owned object. We're just declaring we are going to mutate that object as well.

**Comment by jmmaloney4** [comment]
@MarcoPolo That makes sense. Thanks!
