### ISSUE TITLE
Error Shown in VSCode : add reference here rust-analyzer

### ISSUE THREAD

**Issue by canewsin** [libp2p/rust-libp2p#2348]
When deriving NetworkBehaviour.
This doesn't stop the code compilations.

![Screenshot (23)](https://user-images.githubusercontent.com/26790557/142383128-e238e817-c2bd-448b-9d2c-6c87036cd9d0.png)

Even code examples have these errors.

**Comment by elenaf9** [comment]
I may have found a fix for the error, @canewsin  could you test if you still get it on https://github.com/elenaf9/rust-libp2p/tree/swarm-derive/inject-dial-error?
If this solves it, I'll do a PR.

**Comment by canewsin** [comment]
Issue Fixed.

**Comment by mxinden** [comment]
Closing here since https://github.com/libp2p/rust-libp2p/pull/2349 is merged.

**Comment by rkuhn** [comment]
@mxinden Since this is a show-stopper for releasing against libp2p 0.41, would it be possible to release libp2p-swarm-derive 0.26.1 soon?

**Comment by mxinden** [comment]
I can cut `v0.41.2` with this fix. Before I do, would you mind expanding on why this is a _show-stopper_ @rkuhn? I categorized this as a lint thus far.

**Comment by rkuhn** [comment]
Hmm, you’re right — I didn’t actually try building with rustc when I saw the kind of error (which usually means that without a `&` there is a type error). It is somewhat confusing that all references implement Clone, since that impl is so rarely used.

In any case, I depend on rust-analyzer, and I learnt to only trust its output when there are no errors in the project at all, which means I’d still prefer this to be released sooner rather than later :-)

**Comment by rkuhn** [comment]
Perhaps 0.26.1 of this crate is enough for starters, libp2p 0.41.2 could have more things.

**Comment by mxinden** [comment]
I plan to release `v0.42.0` next week. Is that good enough @rkuhn?

**Comment by rkuhn** [comment]
sure!
