### ISSUE TITLE
swarm/src/protocols_handler: Make `ProtocolsHandlerEvent` depend on `ProtocolsHandler only

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#2389]
Today `ProtocolsHandlerEvent` depends on 4 trait parameters.

https://github.com/libp2p/rust-libp2p/blob/b6c82a499c185eae6af716a5ecae2a8c7a4b6476/swarm/src/protocols_handler.rs#L311-L324

I think it is worth exploring simplifications, e.g. having `ProtocolsHandlerEvent` depend on a `ProtocolsHandler` implementation only:

```rust
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum ProtocolsHandlerEvent<THandler: ProtocolsHandler> {
    /// Request a new outbound substream to be opened with the remote.
    OutboundSubstreamRequest {
        /// The protocol(s) to apply on the substream.
        protocol: SubstreamProtocol<THandler::OutboundProtocol, THandler::OutboundOpenInfo>,
    },

    /// Close the connection for the given reason.
    Close(THandler::Errror),

    /// Other event.
    Custom(THandler::OutEvent),
}
```

Note that this might clash with the various `ProtocolsHandlerEvent::map_xxx` methods, as they assume being able to map individual trait parameters.

Proposed by @elenaf9 in https://github.com/libp2p/rust-libp2p/pull/2059#discussion_r770527101.

**Comment by drHuangMHT** [comment]
Update: `ProtocolHandler` has been renamed to `ConnectionHandler`.  
Just attempted to do this but the compiler denied an inobvious equality: associated types of `ToggleConnectionHandler<TInner>` and associated types of `TInner`. This is expected, because the wrapper and inner are different after all. But this makes it impossible to remove all generic parameters of `ConnectionHandlerEvent` without removing `ToggleConnectionHandler`.

**Comment by thomaseizinger** [comment]
Three of these trait parameters will go away eventually through other refactorings:

- `Close`: https://github.com/libp2p/rust-libp2p/issues/3591
- `TOutboundOpenInfo`: https://github.com/libp2p/rust-libp2p/issues/3268
- `TConnectionUpgrade`: https://github.com/libp2p/rust-libp2p/issues/2863

**Comment by thomaseizinger** [comment]
Closing this as a result.
