### ISSUE TITLE
inject_dial_failure called with wrong peer ID

### ISSUE THREAD

**Issue by rkuhn** [libp2p/rust-libp2p#2425]
When dialling PeerA at a listen address of PeerB, `inject_dial_failure` is called with the peer ID of PeerB (and an error “Dial error: Invalid peer ID”). Proper error handling on the behaviour side would be easier if the peer ID of PeerA was used here (i.e. the expected ID, not the negotiated one).

**Comment by mxinden** [comment]
Agreed that the above would be more intuitive.

Actually, the comment on `PendingOutboundConnectionError` is wrong as of today

https://github.com/libp2p/rust-libp2p/blob/71a54d8227a0043c26f83c61bceb68b174a343b3/core/src/connection/pool.rs#L202-L203

given that we return the actual peer ID instead of the expected one as you noted above

https://github.com/libp2p/rust-libp2p/blob/71a54d8227a0043c26f83c61bceb68b174a343b3/core/src/connection/pool.rs#L832-L837

How about we:

1. Call `inject_dial_failure` with the expected peer ID.
2. Include the actual peer ID in the `DialError`.

What do you think @rkuhn? Do you want to create a patch?

**Comment by rkuhn** [comment]
sure, will do today or tomorrow — good idea of adding to DialError (as an `Option<PeerId>`, I think)

**Comment by mxinden** [comment]
Closing here given that https://github.com/libp2p/rust-libp2p/pull/2428 is merged.
