### ISSUE TITLE
Multiple transport support

### ISSUE THREAD

**Issue by YoshieraHuang** [libp2p/rust-libp2p#2538]
Does rust-libp2p support multiple transports as [here](https://docs.libp2p.io/concepts/transport/#supporting-multiple-transports) descrbies?

**Comment by mxinden** [comment]
Yes, see https://github.com/libp2p/rust-libp2p/tree/master/transports.

**Comment by YoshieraHuang** [comment]
Yes，I know multiple kinds of transports are supported。Can swarm listen to multiple multiaddrs which may use different kind of transports simultaneously？



| |
yoshierahuang
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Max ***@***.***> |
| 日期 | 2022年02月26日 00:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [libp2p/rust-libp2p] Multiple transport support (Issue #2538) |

Yes, see https://github.com/libp2p/rust-libp2p/tree/master/transports.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by elenaf9** [comment]
Yes, [Transport::or_transport](https://docs.rs/libp2p/latest/libp2p/trait.Transport.html#method.or_transport) / [OrTransport](https://docs.rs/libp2p/latest/libp2p/core/transport/struct.OrTransport.html) allows you to use multiple transports. If you then dial / listen on an address, the transports are tried sequentially if they support this address. If the first transport supports it, it is used, otherwise the second transport is tried. 
One example for this is implemented in the `libp2p::development_transport` function to support TCP and websockets:
https://github.com/libp2p/rust-libp2p/blob/b1859464c956824c45cb9767486af1334fab2a13/src/lib.rs#L204-L207

Does this answer the question?

**Comment by YoshieraHuang** [comment]
> Yes, [Transport::or_transport](https://docs.rs/libp2p/latest/libp2p/trait.Transport.html#method.or_transport) / [OrTransport](https://docs.rs/libp2p/latest/libp2p/core/transport/struct.OrTransport.html) allows you to use multiple transports. If you then dial / listen on an address, the transports are tried sequentially if they support this address. If the first transport supports it, it is used, otherwise the second transport is tried. One example for this is implemented in the `libp2p::development_transport` function to support TCP and websockets:
> 
> https://github.com/libp2p/rust-libp2p/blob/b1859464c956824c45cb9767486af1334fab2a13/src/lib.rs#L204-L207
> 
> Does this answer the question?

Yes, This is what i want.
