### ISSUE TITLE
How about moving `wasm-timer` into the rust-libp2p/misc ?

### ISSUE THREAD

**Issue by koushiro** [libp2p/rust-libp2p#2653]
How about moving [wasm-timer](https://github.com/tomaka/wasm-timer) into the `rust-libp2p/misc` dir, like #2641 did.

/cc @mxinden @tomaka

**Comment by koushiro** [comment]
Maybe [quicksink](https://github.com/paritytech/quicksink) also needs to be moved to the misc dir?

**Comment by mxinden** [comment]
> How about moving [wasm-timer](https://github.com/tomaka/wasm-timer) into the `rust-libp2p/misc` dir

I would much rather like to see it replaced with a timing library that is still actively maintained. See https://github.com/libp2p/rust-libp2p/issues/2497#issuecomment-1038923700. Contributions would be very much appreciated.



> Maybe [quicksink](https://github.com/paritytech/quicksink) also needs to be moved to the misc dir?

Any particular reason for that?


----

In general, while I am a big fan of mono-repos, I would like to:

- Keep things useful (and used) outside of libp2p outside the monorepo.
- Ideally reduce the maintenance work on the rust-libp2p maintainers rather than increasing it.

**Comment by koushiro** [comment]
> > Maybe [quicksink](https://github.com/paritytech/quicksink) also needs to be moved to the misc dir?
> 
> Any particular reason for that?

[quicksink](https://github.com/paritytech/quicksink) is used for libp2p-websocket, but this repo has been archived by paritytech.

I'm not sure if there is an alternative of this library.

**Comment by mxinden** [comment]
Instead of moving another generic library into the rust-libp2p monorepo, I think we can replace the use of quicksink in `libp2p-websocket` instead. Not a strong opinion, though would prefer not increasing the maintenance work on us long term.

**Comment by thomaseizinger** [comment]
I'll close this as not planned. `wasm-timer` is unmaintained and we are moving away from it in https://github.com/libp2p/rust-libp2p/pull/3973 at least for gossipsub.
