### ISSUE TITLE
src/lib: Add libp2p-tls to development_transport

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#3060]
Once `libp2p-tls` is no longer an `alpha` (which it is today, see below) I suggest we add it to our `development_transport` convenience method.

Thoughts?

https://github.com/libp2p/rust-libp2p/blob/4d1b165982f15191ee5bbe3d98663dbfa0548338/transports/tls/Cargo.toml#L1-L6

https://github.com/libp2p/rust-libp2p/blob/4d1b165982f15191ee5bbe3d98663dbfa0548338/src/lib.rs#L182

**Comment by thomaseizinger** [comment]
Those functions are problematic IMO, at least how they are currently used (inside tests and examples), see https://github.com/libp2p/rust-libp2p/pull/3056.

I also think the naming is off. "development" to me suggests that this is something I use during testing but not in production.

It also doesn't fit in well with the executor-specific features that we are currently implementing.

I can see a "recommended" stack being useful but then it should be rename and I don't think we should use the recommended stack in tests and examples.

Tests should use a transport as simple as possible (probably memory + plaintext).

For the larger examples, using that recommended transport works because we are already in the libp2p crate. For all other transports, we would introduce a circular dependency again. We can either move those examples or inline it there.

In general, I'd prefer if we make composing upgrades simpler and less verbose so the value of these convenience functions is basically 0 and we don't lose anything from deleting them.

**Comment by thomaseizinger** [comment]
Tests will eventually use https://github.com/libp2p/rust-libp2p/pull/2888.

For the examples, we could move away from regular cargo examples and instead introduce an `examples` directory that has multiple crates in it. Those would probably be easier to maintain because they would have the exact same layout as a user's application. We'd just specify only the features we need in them which makes them easier to run too.

**Comment by thomaseizinger** [comment]
Cross-referencing an idea here: https://github.com/libp2p/rust-libp2p/pull/3635#issuecomment-1477374636

**Comment by thomaseizinger** [comment]
Closing this in favor of https://github.com/libp2p/rust-libp2p/issues/3657.
