### ISSUE TITLE
Have a function to generate a peer_ID from a newly generated public key (with an associated private key)

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#338]
https://github.com/libp2p/rust-libp2p/blob/master/core/src/peer_id.rs

I don't have a public key on record, I have Ethereum addresses (which is the hash of a public key). So for convenience it seems it would be nice to have a function to generate a peer_ID from a newly generated public key (with an associated private key).

**Comment by tomaka** [comment]
The `SecioKeyPair` type allows doing that: https://github.com/libp2p/rust-libp2p/blob/master/secio/src/lib.rs#L157-L253
However it still requires some improvements ; for example it doesn't allow exporting the private key of a generated ed25519 pair.

We probably don't want to depend on any cryptographic library in the `core` crate though, because they tend to create some compilation nightmares.

**Comment by jamesray1** [comment]
Hmm, given that ed25519 has advantages over RSA and secp256k1, it would be be handy to be able to export the private key of a generated ed25519 pair...

**Comment by tomaka** [comment]
I'm going to close this in favour of #807
