### ISSUE TITLE
Make sure yamux closes all substreams on underlying error

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#346]
Make sure that `yamux` closes all the active substreams when the underlying socket produces an error.
Write tests for this.

**Comment by tomaka** [comment]
The "write tests" part still needs to be addressed.

**Comment by tomaka** [comment]
Fixed by https://github.com/paritytech/yamux/pull/10

**Comment by romanb** [comment]
For what it is worth, [this is done here](https://github.com/paritytech/yamux/blob/0ddf9a33c1f92c7879d3423ec126e3f57261c438/src/connection.rs#L326-L347). I think if there are doubts whether this works properly, we should create an issue over at `paritytech/yamux`. Feel free to reopen if you think otherwise.
