### ISSUE TITLE
CHANGELOG.md enhancements

### ISSUE THREAD

**Issue by BigLep** [libp2p/rust-libp2p#3531]
## Description
When looking at https://github.com/libp2p/rust-libp2p/blob/master/CHANGELOG.md with fresh eyes, a few minor things stood out:

1. We don't have a TOC at the top.  I assume that's because we're relying on one to use tooling from their viewer:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/85411/221712803-849fdf0a-daed-4010-91c7-aa8cfce5c48a.png">
2. Heading levels changed at v45.0
<img width="334" alt="image" src="https://user-images.githubusercontent.com/85411/221712882-1327e563-7db2-4842-9372-616daf5f2fab.png">
3. We stopped including a date in v44.0.  (I assume that's intentional to to make it quicker for manually creating an anchor link to a specific version.

## Motivation
This isn't critical.  Feel free to resolve.  I'm just posting in case this wasn't intentional or we do further adjustments to changelog.md in the future.

I do think we should make sure we do a good job of highlighting why a certain release matters in https://github.com/libp2p/rust-libp2p/blob/master/CHANGELOG.md#libp2p-facade-crate

## Are you planning to do it yourself in a pull request?
No

**Comment by mxinden** [comment]
Thanks for the feedback.

(1) is fine in my eyes, i.e. toc tooling to be provided by viewing tool (e.g. github)

(2) will be fixed with https://github.com/libp2p/rust-libp2p/pull/3561

(3) easier and date is redundant, given that the file is checked into version control

Agreed with the motivation. We started calling out larger sub-crate changes on the main changelog only recently.
