### ISSUE TITLE
kad: Make implementation modules private

### ISSUE THREAD

**Issue by thomaseizinger** [libp2p/rust-libp2p#3608]
## Description

Similar to https://github.com/libp2p/rust-libp2p/issues/3494, we want to make the public API of kademlia as small as possible.

## Motivation

To have the ability to refactor implementation details without causing breaking changes.

## Are you planning to do it yourself in a pull request?

lNo.

**Comment by tcoratger** [comment]
@thomaseizinger In this situation: 
- Do you prefer to deprecate modules inside `kad` one by one in different PRs, as is done for `gossipsub`?
- Or do you want to do a unique PR which deprecates all modules together? 

From my side, I think that it may be better to do it all at once in order to store all the information on the same PR, what do you think?

**Comment by thomaseizinger** [comment]
> @thomaseizinger In this situation: 
> - Do you prefer to deprecate modules inside `kad` one by one in different PRs, as is done for `gossipsub`?
> - Or do you want to do a unique PR which deprecates all modules together? 
> 
> From my side, I think that it may be better to do it all at once in order to store all the information on the same PR, what do you think?

Yes, deprecating them in one PR makes a lot of sense.

**Comment by tcoratger** [comment]
@thomaseizinger Sure, will work on the topic.
