### ISSUE TITLE
Provide Documentation

### ISSUE THREAD

**Issue by gnunicorn** [libp2p/rust-libp2p#368]
Most, if not all, of the crates have nice inline-docs, however, those aren't easily accessible until we release our crates. Providing a README for each crate containing the same information seem redundant. Let's figure out a nice way to provide (online) docs until that point. Maybe something as simple as running `cargo docs` on every merge and publish the result somewhere automatically.

**Comment by jamesray1** [comment]
Rather than creating a new issue, I'll just post this here:

https://github.com/libp2p/rust-libp2p/blob/4592d1b21ef8bd41a8176ad651feb1aa6cb1b377/core/src/swarm.rs#L28

It would be helpful to give examples of how to actually create a swarm. Context: writing gossipsub here: 

https://github.com/jamesray1/rust-libp2p/blob/a0601a0b0893bacc279e0d59b147cb07918c0ebb/gossipsub/src/lib.rs#L113

**Comment by gnunicorn** [comment]
looks good, @jamesray1. Can't say much about whether it correct, but highly appreciate you taking the time adding documentation to the project!

**Comment by jamesray1** [comment]
Yeah no it's not all correct. I read the libp2p-core readme, that helped to identify why it's not correct and how to correct it.

**Comment by romanb** [comment]
What are the criteria for considering this issue "resolved"?

**Comment by tomaka** [comment]
I think the situation was more catastrophic when this issue was opened.
