### ISSUE TITLE
what's the requirement to build this repo?

### ISSUE THREAD

**Issue by guanqun** [libp2p/rust-libp2p#423]
I did a `cargo build` with stable rust 1.28.0 but it says:

```
error[E0061]: this function takes 1 parameter but 0 parameters were supplied
   --> /Users/q/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.10/src/reactor/poll_evented.rs:276:39
    |
276 |         if let Async::NotReady = self.poll_read() {
    |                                       ^^^^^^^^^ expected 1 parameter
```

looks like the tokio version is incorrect?

**Comment by gnunicorn** [comment]
Things are changing fast at the moment, so we are always require latest rust stable for now. Aside from that we define the dependencies in the `Cargo.toml` as usual.

Running it here, this is pulling `tokio-core 0.1.17`, which is what cargo should do if that is the latest version and as per our spec saying to use `tokio-core = "0.1"`. I am not sure why your version intends to build such an old version of tokio core and it confuses me that said version should contain such a change. Either way, this isn't because of anything libp2p does.

Please run `cargo update` and try again. This should pull all latest compatible versions of dependencies we require. If you still run into issues, try removing the `.cargo/registry` cache altogether and try again. If this is still an issue after, feel free to reopen this ticket.

**Comment by guanqun** [comment]
Thanks for your detailed reply, I didn't notice the fact that `Cargo.lock` for libraries is not committed into the repo so that it relies on my local `cargo update`. and I checked this repo long time ago... Now it can compile successfully.
