### ISSUE TITLE
feat(swarm): allow `NetworkBehaviour` to report remote address

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4302]
## Description

Allow a `NetworkBehaviour` to report the external address of a remote peer to other `NetworkBehaviour`s.

Possible approach (though up for discussion):

- Extend `ToSwarm` with `ToSwarm::NewExternalAddrOfPeer`.
- Have `libp2p-identify` emit the new event.
- Extend `FromSwarm` with `FromSwarm::NewExternalAddrOfPeer`.
- Have `libp2p-kad` consume the new event.

## Motivation

- Allows `libp2p-identify` to e.g. tell `libp2p-kad` of an external address of a remote peer and thus allows `libp2p-kad` to track that address in its Kademlia routing table.

## Are you planning to do it yourself in a pull request?

No

**Comment by dariusc93** [comment]
I assume this will not just be limited to just `libp2p-identify` emitting the event but any behaviour that has obtain a peer remote address?

**Comment by mxinden** [comment]
Yes, any `NetworkBehaviour`, not constrained to `libp2p-identify`.

**Comment by thomaseizinger** [comment]
> I assume this will not just be limited to just `libp2p-identify` emitting the event but any behaviour that has obtain a peer remote address?

Yes although there aren't that many which can discover "new" addresses. I'd say it is unnecessary to emit an event for an address we just connected to for example.

Behaviours I can think of that can discover new addresses are:

- identify
- kademlia
- mDNS
- rendezvous

**Comment by StemCll** [comment]
Taking a look into this

**Comment by mxinden** [comment]
### (1) `libp2p-request-response` consuming `FromSwarm::NewExternalAddrOfPeer`

Another consumer of the new `FromSwarm::NewExternalAddrOfPeer` can be `libp2p-request-response`.

This could feed into its `addresses` cache:

https://github.com/libp2p/rust-libp2p/blob/c6984dd51db6be8e260be1494f2bbc9052a42206/protocols/request-response/src/lib.rs#L336-L337

Though we would need some garbage collection mechanism along the lines of `libp2p-identify`:

https://github.com/libp2p/rust-libp2p/blob/c6984dd51db6be8e260be1494f2bbc9052a42206/protocols/identify/src/behaviour.rs#L53-L54

### (2) Generic `Swarm::add_external_addr_of_peer` triggering `FromSwarm::NewExternalAddrOfPeer`

If we go one step further and add `Swarm::add_external_addr_of_peer` we could deprecate the protocol specific methods in `libp2p-request-response` and `libp2p-kad`:

https://github.com/libp2p/rust-libp2p/blob/c6984dd51db6be8e260be1494f2bbc9052a42206/protocols/request-response/src/lib.rs#L443-L450

https://github.com/libp2p/rust-libp2p/blob/c6984dd51db6be8e260be1494f2bbc9052a42206/protocols/kad/src/behaviour.rs#L510-L527

---

@thomaseizinger @StemCll  thoughts on (1) and (2)?

@StemCll I suggest **not** doing (1) or (2) as part of https://github.com/libp2p/rust-libp2p/pull/4371 to keep the pull request's scope small.

**Comment by thomaseizinger** [comment]
Instead of (1), I thought we wanted to do https://github.com/libp2p/rust-libp2p/issues/4103?

**Comment by mxinden** [comment]
In my eyes no protocol should depend on #4103. In other words, all protocols should function without #4103. I don't think we should move away from the current convention where every protocol keeps its own cache of peer information.

In my eyes #4103 is mostly for users to interact with. E.g. retrieving the currently connected nodes, their addresses, ...

**Comment by thomaseizinger** [comment]
> In my eyes no protocol should depend on #4103. In other words, all protocols should function without #4103. I don't think we should move away from the current convention where every protocol keeps its own cache of peer information.
> 
> In my eyes #4103 is mostly for users to interact with. E.g. retrieving the currently connected nodes, their addresses, ...

Agreed in principle.

At the moment, `libp2p-request-response` has APIs that IMO belong onto #4103, like `add_address`.

I am not against adding a cache of discovered addresses although that might be better implemented on a `Swarm` level as an implementation detail without an external API so that not every protocol has to re-implement it.

Once we have #4103, I'd propose to remove the `add_address` API on `libp2p-request-response`.

Protocols should be able to perform their primary function in isolation but for me, that excludes keeping an address book. I can use `libp2p-request-response` just fine if I've made a dial with addresses to the peer already. Thus, I don't think that is conflicting and from that PoV, I don't see why `libp2p-request-response` should be a consumer of this new event.

**Comment by thomaseizinger** [comment]
I've commented with a different idea on https://github.com/libp2p/rust-libp2p/pull/4371: Instead of removing the `add_address` API on `libp2p-request-response` as a result of #4103, we probably should instead add a function to `Swarm` that allows users to trigger this event. That is how we've previously solved this. Behaviours like kademlia & request-response can then have an internal state where they respond to the event and (temporarily) store the address.

**Comment by thomaseizinger** [comment]
> I've commented with a different idea on #4371: Instead of removing the `add_address` API on `libp2p-request-response` as a result of #4103, we probably should instead add a function to `Swarm` that allows users to trigger this event. That is how we've previously solved this. Behaviours like kademlia & request-response can then have an internal state where they respond to the event and (temporarily) store the address.

I just realised that this is exactly (2) from above. Sorry @mxinden, I must have not read the above comment properly 😅

Or as they say: Great minds think alike 😇

**Comment by thomaseizinger** [comment]
Instead of sharing addresses, should we be thinking about sharing peer records?

**Comment by mxinden** [comment]
Given that we don't support it in `libp2p-identity` yet, would you construct the peer record locally? If so, what would you set on `PeerRecord::envelope`?

https://github.com/libp2p/rust-libp2p/blob/7d1d67cad3847a845ad50d9e56b3b68ca53f5e22/core/src/peer_record.rs#L18-L27

Long term, yes, I think this mechanism should use peer records. Short term, to not block it on the role out of peer records, I suggest using addresses only.

**Comment by thomaseizinger** [comment]
You can't construct it locally because it needs to be signed so yeah it would have to come from `libp2p-identify` but that is a trivial addition compared to this feature.

I thought of it because we will need a mechanism for sharing peer records for anything that is like https://github.com/libp2p/specs/discussions/587 and it is kind of unfortunate to design a new API that we already know will be obsoleted.

**Comment by thomaseizinger** [comment]
For reference, here is the ticket: https://github.com/libp2p/rust-libp2p/issues/4017

**Comment by mxinden** [comment]
> You can't construct it locally because it needs to be signed so yeah it would have to come from `libp2p-identify` but that is a trivial addition compared to this feature.

`libp2p-identify` is not the only protocol that can discover addresses of remote peers. E.g. `libp2p-kad` can do so as well, e.g. on [`Kademlia::find_closest`](https://github.com/libp2p/rust-libp2p/blob/3a0f0c292ae2d8093d276d57028d15835094e1e0/protocols/kad/src/behaviour.rs#L1110-L1125). Unfortunately the libp2p Kademlia specification only supports plain addresses today. See https://github.com/libp2p/specs/blob/master/kad-dht/README.md.

> and it is kind of unfortunate to design a new API that we already know will be obsoleted.

With the above in mind, I don't think the new API will be obsolete any time soon. I don't see the large libp2p DHT deployments (e.g. IPFS) move to signed peer records any time soon.

**Comment by thomaseizinger** [comment]
Yeah that is fair! I guess once we have `non-exhaustive`, we can easily add more variants :)
