### ISSUE TITLE
feat(misc/server): add HEALTHCHECK to Dockerfile

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4444]
We should add a `HEALTHCHECK` to our `Dockerfile`.

https://docs.docker.com/engine/reference/builder/#healthcheck

https://github.com/libp2p/rust-libp2p/blob/423fb2fd5068151f29a4b443ff92075c1e3a8f04/misc/server/Dockerfile#L1-L16

Maybe we can bundle https://github.com/mxinden/libp2p-lookup/ into the image, or add similar functionality to the `libp2p-server` binary.

//CC @mcamou

@mcamou if I understand correctly this is not critical. In case the config can not be parsed the command already returns a non-zero exit code. In case connections can not be established or there are no inbound Kademlia requests, we [have Grafana alerting](https://protocollabs.grafana.net/d/b5efff5e-f389-4e2f-b729-201432451dc6/rust-libp2p-alerts?orgId=1&from=now-7d&to=now&tab=alert). Correct me if I am wrong.

**Comment by mcamou** [comment]
It's "critical" in the sense that at the moment not having a built-in healthcheck means that we have to hack around our deployment configurations so that deployment doesn't fail, since after deploying a new version we wait until the healthcheck returns true. We try to keep things as uniform as possible between Kubo and `rust-libp2p-server`, so this is one more thing where they are different.

**Comment by thomaseizinger** [comment]
A simple health check could be to just curl the `/metrics` endpoint. If that one is there, the binary is running :)

**Comment by gmasgras** [comment]
> A simple health check could be to just curl the `/metrics` endpoint. If that one is there, the binary is running :)

Using `libp2p-lookup` sounds like a better option, IMHO, since it connects to the node rather than fetching metrics via http. We'd also need to bundle `curl` or similar if we take the `/metrics` route since health checks run inside the container.

**Comment by mcamou** [comment]
We actually don't need the `HEALTHCHECK` line added to the Dockerfile (which would be a challenge since the port numbers and node ID are set up dynamically). We would just need the proper tool (`curl` or `libp2p-lookup`, or modifying `libp2p-server`) to be bundled into the container, we can then add the healthcheck when starting it up.

**Comment by thomaseizinger** [comment]
Resolved in #4466.
