### ISSUE TITLE
dns: make `DnsConfig::custom` infallible

### ISSUE THREAD

**Issue by mxinden** [libp2p/rust-libp2p#4462]
With https://github.com/libp2p/rust-libp2p/pull/4441/ we can now make the method infallible.

**Comment by thomaseizinger** [comment]
@p0mvn Mind commenting quickly on this issue so I can assign you?

**Comment by p0mvn** [comment]
Sure

**Comment by ManojJiSharma** [comment]
Hi, Is this issue still available? I want to resolve this, So If it is then let me know more details about the Issue.

**Comment by thomaseizinger** [comment]
> Hi, Is this issue still available? I want to resolve this, So If it is then let me know more details about the Issue.

Hi @ManojJiSharma !

There is already a PR at https://github.com/libp2p/rust-libp2p/pull/4464 which is just waiting for the merge window of breaking changes to open but it is otherwise ready :)

Here are some other issues that you may want to look at:

- https://github.com/libp2p/rust-libp2p/issues/4345
- https://github.com/libp2p/rust-libp2p/issues/4489
