### ISSUE TITLE
Updated examples coming back?

### ISSUE THREAD

**Issue by jayavanth** [libp2p/rust-libp2p#572]
I just started using this library and I noticed that the examples have been removed. Are new examples coming soon? Appreciate any more documentation to help get me started with the library. I'm planning to build a [p2p blockchain](https://medium.com/@mycoralhealth/code-a-simple-p2p-blockchain-in-go-46662601f417) except with rust-libp2p

**Comment by mgoelzer** [comment]
@tomaka I want to point people to the examples in a slide for my Web3 talk (on Oct 24th), even if they are missing in the head of master at the time of the talk.  When they do come back, will `/examples/` still be the right path to find them?

@jayavanth I think the examples were removed in #565 because they are working on a new API.  So, you could check out any version of the repo before that PR and use those older examples to learn about rust-libp2p.  Or look at the go examples in https://github.com/go-libp2p-examples since the concepts are fundamentally the same.

**Comment by tomaka** [comment]
> When they do come back, will /examples/ still be the right path to find them?

Yes!

> I think the examples were removed in #565 because they are working on a new API.

Indeed. We realize it's really not great to do that, but big changes had to be made to make the library more predictable, and if we allow ourselves to break things we can go ten times faster than if we have to stay backwards compatible.
