### ISSUE TITLE
Expand identity keypairs with more functionalities

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#807]
- Add the possibility to generate secp256k1 and RSA keys.
- Add the possibility to export the generated private key, with hopefully an API that's not too easy to misuse.
- Maybe add some utility functions to load/save a private key to file, with the file having the right permissions (400).
- As a more general thing, try to improve the usability of this struct.

**Comment by tomaka** [comment]
> Maybe add some utility functions to load/save a private key to file, with the file having the right permissions (400).

What I mean by that is that the content of this file could be moved to libp2p:
https://github.com/paritytech/substrate/blob/ecfc6f14846bbe3778573d2ea1b9613090fcd91c/core/network-libp2p/src/secret.rs

**Comment by tomaka** [comment]
We should also consider moving this type to the core, or in a general `libp2p-crypto` library.

**Comment by burdges** [comment]
I'm ambivalent about RSA but sure why not.  :)

We should not really encourage using secp256k1 at the transport layer, primarily because secp256k1 implementations have issues with side channels.  I've even heard folks who really know secp256k1 claim only one good implementation exists.  Could secp256k1 have some feature gate with a warning?

**Comment by romanb** [comment]
An update in the light of https://github.com/libp2p/rust-libp2p/pull/972 where `SecioKeyPair` has been removed:

> Add the possibility to generate secp256k1 and RSA keys.

Support for generating Secp256k1 keys is there. RSA keys cannot easily be generated since ring does not have support for doing that yet (https://github.com/briansmith/ring/issues/219). I don't think that is actually important though.

> Add the possibility to export the generated private key, with hopefully an API that's not too easy to misuse.

Both ed25519 and secp256k1 identity keypairs provide access to the secret key bytes, e.g. for storage. These are also the keypairs that can be generated through code, so right now there is a sensible symmetry: RSA keypairs must be created externally and cannot be exported / stored from code, whereas ed25519 and secp256k1 keypairs can be generated in code and also exported for storage.

> Maybe add some utility functions to load/save a private key to file, with the file having the right permissions (400).

I think that is best left to a separate libp2p crate (e.g. `libp2p-keystore` or similar) or even an external crate. In any case it is not something that needs to be in `libp2p-core` and hence should probably not be there IMHO.

> As a more general thing, try to improve the usability of this struct.

I don't know what that entails in the context of the new `libp2p_core::identity::Keypair`.

Overall, for clarity I would suggest to create new issues for any remaining TODOs in the context of the current state of the codebase and close this ticket.

**Comment by tomaka** [comment]
Nit-pick: we're missing `identity::Keypair::ed25519_from_der()`.
After that we can indeed close this issue I think.

**Comment by romanb** [comment]
> Nit-pick: we're missing identity::Keypair::ed25519_from_der().

There doesn't really seem to be any demand though. I'd prefer to close this issue and if necessary follow up with new, more concrete tickets for specific enhancements when they are needed. Feel free to reopen if you disagree.
