### ISSUE TITLE
RFC: inlining

### ISSUE THREAD

**Issue by jamesray1** [libp2p/rust-libp2p#897]
This library has lots of inline attributes on functions. It seems like the pattern is that they are added when a function is only a few lines. However, from https://internals.rust-lang.org/t/when-should-i-use-inline/598/8 it seems like it is better to not use it in a library, let the compiler decide, and let library users use link-time optimisation if they want to have a super-fast binary. Any thoughts?

**Comment by tomaka** [comment]
I didn't comment on this earlier because the answer is that I don't know.

As far as I know, putting `#[inline]` makes it possible to inline function calls across crates by embedding the source code of the inlined function within the `.rlib`.

The counter-argument is that link-time optimisation does the same anyway, except at a different step of the compilation, and that therefore we don't need to inline across crates.

**Comment by jamesray1** [comment]
Closing as it seems we agree that inlining isn't needed.

**Comment by tomaka** [comment]
Well, I don't know if what I said it's true.
The only real answer would be to experiment with/without `#[inline]` and see the consequence on the bytecode.

**Comment by romanb** [comment]
I think we do have a rough consensus by now that explicit `#[inline]` should be the exception in cases where benchmarking confirmed a bottleneck or hot code path that should be optimised through inlining across crates even in cases without link-time optimisation.
