### ISSUE TITLE
Test Infrastructure

### ISSUE THREAD

**Issue by folsen** [libp2p/rust-libp2p#9]
We want some way to easily create a large and distributed (over IP-space) simulated network that allows for easy testing of peer discovery, routing and other aspects.

From initial research, following tools seem suitable:

* https://gns3.com
* https://www.nsnam.org/ (NS-3)

**Comment by tomaka** [comment]
cc @kirushik

**Comment by tomaka** [comment]
Just learned about http://mininet.org, putting it here as a note.

**Comment by tomaka** [comment]
There's also https://github.com/canndrew/netsim
It's under GPL, but since we'd use it as a binary, it doesn't matter.

**Comment by tomaka** [comment]
Nevermind. We have to integrate it into our code, which is problematic.

**Comment by tomaka** [comment]
The author changed the license to MIT. 🙏

**Comment by kirushik** [comment]
Just another post with overview of possible approaches: http://www.brianlinkletter.com/build-your-own-network-simulator-using-open-source-devops-tools/

But for me it looks like netsim covers almost every usecase I can think of (NAT routers, packet loss and latency issues), so probably let's start with trying that one?

**Comment by rubdos** [comment]
Another one worth considering would be [OMNeT++](https://omnetpp.org/) possibly together with [OverSim](http://www.oversim.org/), although I'm not sure about the scope of the latter.

I just had a quick look at their license though, looks like "non-free" software (i.e., GPL-ish for non-commercial users, with the usual vagueness about who's a commercial user). Still leaving the note because it may be of interest to some.

**Comment by mxinden** [comment]
I am closing here since we now have interoperability tests via Testground. Even though just the start, I think this infrastructure is enough to build advanced tests.

See https://github.com/libp2p/test-plans/tree/master/ping for details.
