### ISSUE TITLE
Somehow unify noise::Keypair and secio::KeyPair

### ISSUE THREAD

**Issue by tomaka** [libp2p/rust-libp2p#903]
It feels stupid to have duplicates of all the cryptographic functions.
However things are a bit blurry in terms of API.

**Comment by burdges** [comment]
As I mentioned elsewhere, we should hide SECIO behind some scary sounding feature flag so that nobody uses it going forward.  

We would likely care about roughly this issue whenever we add a post-quantum ephemeral key exchange, probably Kyber:  https://pq-crystals.org/kyber/  

Also, if we ever add TLS 1.3 integration for all these web-like transports, but I've kinda changed my mind about TLS 1.3 making sense because It'd primarily serve to better obfuscate polkadot traffic and we'd do better with an actual pluggable transports scheme.

**Comment by romanb** [comment]
Closed by https://github.com/libp2p/rust-libp2p/pull/972
